<a href="https://colab.research.google.com/github/tharun7781/Data-Science-Edukron/blob/main/NumPy_Assignment_Banking_Industry_Analysis_Questions_Only.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [115]:
import numpy as np

In [116]:
#Question 1: Array Creation and Manipulation
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [117]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [118]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [119]:
np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [120]:
#Question 2: Array Attributes and Information

In [121]:
import numpy as np

In [122]:
banking_data = np.array([[2000,1000,1500,100],
                       [1500,1000,2000,500],
                       [1500,1000,2000,1700]])

In [123]:
banking_data.shape

(3, 4)

In [124]:
banking_data.dtype

dtype('int64')

In [125]:
banking_data.size

12

In [126]:
banking_data.ndim

2

In [127]:
banking_data.nbytes

96

In [128]:
#Question 3: Indexing and Slicing

In [129]:
banking_data[0]

array([2000, 1000, 1500,  100])

In [130]:
banking_data[-1]

array([1500, 1000, 2000, 1700])

In [131]:
banking_data[:, 1]

array([1000, 1000, 1000])

In [132]:
banking_data[:4, :3]

array([[2000, 1000, 1500],
       [1500, 1000, 2000],
       [1500, 1000, 2000]])

In [133]:
banking_data[1:4]

array([[1500, 1000, 2000,  500],
       [1500, 1000, 2000, 1700]])

In [134]:
#Question 4: Mathematical Operations

In [135]:
import numpy as np

In [136]:
banking_data = np.array([
    [101, 1000, 25],
    [102, 2000, 30],
    [103, 3000, 28],
    [104, 4000, 35],
    [105, 5000, 32],
    [106, 6000, 29],
    [107, 7000, 40],
    [108, 8000, 36]
])

In [137]:
balances=banking_data[:, 1]

In [138]:
np.sum(balances)

np.int64(36000)

In [139]:
np.median(balances)

np.float64(4500.0)

In [140]:
np.std(balances)

np.float64(2291.28784747792)

In [141]:
np.var(balances)

np.float64(5250000.0)

In [142]:
np.mean(balances)

np.float64(4500.0)

In [143]:
#Question 5: Statistical Functions

In [144]:
credits  = banking_data[:, 2]

In [145]:
np.min(balances), np.max(balances)

(np.int64(1000), np.int64(8000))

In [146]:
np.min(credits), np.max(credits)

(np.int64(25), np.int64(40))

In [147]:
np.percentile(balances,[25,50,75])

array([2750., 4500., 6250.])

In [148]:
np.corrcoef(balances,credits)

array([[1.        , 0.75849625],
       [0.75849625, 1.        ]])

In [149]:
np.cov(balances,credits)

array([[6.00000000e+06, 9.07142857e+03],
       [9.07142857e+03, 2.38392857e+01]])

In [150]:
#Question 6: Array Reshaping and Manipulation

In [151]:
banking_data = np.array([
    [101, 1000, 25],
    [102, 2000, 30],
    [103, 3000, 28],
    [104, 4000, 35],
    [105, 5000, 32],
    [106, 6000, 29],
    [107, 7000, 40],
    [108, 8000, 36],
     [109, 8000, 36],
     [110, 8000, 36]
])

In [152]:
banking_data.reshape(3, 10)

array([[ 101, 1000,   25,  102, 2000,   30,  103, 3000,   28,  104],
       [4000,   35,  105, 5000,   32,  106, 6000,   29,  107, 7000],
       [  40,  108, 8000,   36,  109, 8000,   36,  110, 8000,   36]])

In [153]:
banking_data.flatten()

array([ 101, 1000,   25,  102, 2000,   30,  103, 3000,   28,  104, 4000,
         35,  105, 5000,   32,  106, 6000,   29,  107, 7000,   40,  108,
       8000,   36,  109, 8000,   36,  110, 8000,   36])

In [154]:
banking_data.T

array([[ 101,  102,  103,  104,  105,  106,  107,  108,  109,  110],
       [1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000, 8000, 8000],
       [  25,   30,   28,   35,   32,   29,   40,   36,   36,   36]])

In [155]:
np.vsplit(banking_data,2)

[array([[ 101, 1000,   25],
        [ 102, 2000,   30],
        [ 103, 3000,   28],
        [ 104, 4000,   35],
        [ 105, 5000,   32]]),
 array([[ 106, 6000,   29],
        [ 107, 7000,   40],
        [ 108, 8000,   36],
        [ 109, 8000,   36],
        [ 110, 8000,   36]])]

In [156]:
np.hsplit(banking_data, 1)

[array([[ 101, 1000,   25],
        [ 102, 2000,   30],
        [ 103, 3000,   28],
        [ 104, 4000,   35],
        [ 105, 5000,   32],
        [ 106, 6000,   29],
        [ 107, 7000,   40],
        [ 108, 8000,   36],
        [ 109, 8000,   36],
        [ 110, 8000,   36]])]

In [157]:
#Question 7: Logical Operations and Filtering

In [158]:
banking_data = np.array([
    [101, 120000, 820, 60],
    [102, 80000, 750, 45],
    [103, 95000, 780, 55],
    [104, 40000, 710, 30],
    [105, 150000, 860, 70],
    [106, 60000, 730, 25],
    [107, 300000, 900, 80],
    [108, 50000, 700, 20]
])

In [159]:
banking_data[banking_data[:,1] > 100000]

array([[   101, 120000,    820,     60],
       [   105, 150000,    860,     70],
       [   107, 300000,    900,     80]])

In [160]:
banking_data[banking_data[:,2] > 800]

array([[   101, 120000,    820,     60],
       [   105, 150000,    860,     70],
       [   107, 300000,    900,     80]])

In [161]:
banking_data[(banking_data[:,3] > 50) & (banking_data[:,2] < 750)]

array([], shape=(0, 4), dtype=int64)

In [162]:
np.sum((banking_data[:,1] >= 10000) & (banking_data[:,1] <= 100000))

np.int64(5)

In [163]:
np.argmax(banking_data[:,2])

np.int64(6)

In [164]:
#Question 8: Sorting and Searching

In [165]:
Q8_1 = banking_data[np.argsort(banking_data[:,1])]
print("Q8.1:\n", Q8_1)

Q8.1:
 [[   104  40000    710     30]
 [   108  50000    700     20]
 [   106  60000    730     25]
 [   102  80000    750     45]
 [   103  95000    780     55]
 [   101 120000    820     60]
 [   105 150000    860     70]
 [   107 300000    900     80]]


In [166]:
Q8_2 = banking_data[np.argsort(-banking_data[:,2])]
print("Q8.2:\n", Q8_2)

Q8.2:
 [[   107 300000    900     80]
 [   105 150000    860     70]
 [   101 120000    820     60]
 [   103  95000    780     55]
 [   102  80000    750     45]
 [   106  60000    730     25]
 [   104  40000    710     30]
 [   108  50000    700     20]]


In [167]:
Q8_3 = np.argsort(banking_data[:,3])
print("Q8.3:\n", Q8_3)

Q8.3:
 [7 5 3 1 2 0 4 6]


In [168]:
Q8_4 = banking_data[np.argsort(-banking_data[:,1])[1]]
print("Q8.4:\n", Q8_4)

Q8.4:
 [   105 150000    860     70]


In [169]:
Q8_5 = banking_data[np.argmin(banking_data[:,3])]
print("Q8.5:\n", Q8_5)

Q8.5:
 [  108 50000   700    20]


In [170]:
#Question 9: Mathematical Functions

In [171]:
np.abs(banking_data)

array([[   101, 120000,    820,     60],
       [   102,  80000,    750,     45],
       [   103,  95000,    780,     55],
       [   104,  40000,    710,     30],
       [   105, 150000,    860,     70],
       [   106,  60000,    730,     25],
       [   107, 300000,    900,     80],
       [   108,  50000,    700,     20]])

In [172]:
np.sqrt(banking_data[:,1])

array([346.41016151, 282.84271247, 308.22070015, 200.        ,
       387.29833462, 244.94897428, 547.72255751, 223.60679775])

In [173]:
np.square(banking_data[:,2])

array([672400, 562500, 608400, 504100, 739600, 532900, 810000, 490000])

In [174]:
np.exp(banking_data[:,3])

array([1.14200739e+26, 3.49342711e+19, 7.69478527e+23, 1.06864746e+13,
       2.51543867e+30, 7.20048993e+10, 5.54062238e+34, 4.85165195e+08])

In [175]:
np.log(banking_data[:,1])

array([11.69524702, 11.28978191, 11.46163217, 10.59663473, 11.91839057,
       11.00209984, 12.61153775, 10.81977828])

In [176]:
#Question 10: Advanced Operations

In [177]:
np.cumsum(banking_data[:,1])

array([120000, 200000, 295000, 335000, 485000, 545000, 845000, 895000])

In [178]:
np.cumprod(banking_data[:,3])

array([            60,           2700,         148500,        4455000,
            311850000,     7796250000,   623700000000, 12474000000000])

In [179]:
np.diff(banking_data[:,1])

array([ -40000,   15000,  -55000,  110000,  -90000,  240000, -250000])

In [180]:
np.gradient(banking_data[:,1])

array([ -40000.,  -12500.,  -20000.,   27500.,   10000.,   75000.,
         -5000., -250000.])

In [181]:
np.histogram(banking_data[:,1], bins=5)

(array([4, 2, 1, 0, 1]),
 array([ 40000.,  92000., 144000., 196000., 248000., 300000.]))

In [182]:
#Question 11: Random Numbers and Simulation

In [183]:
# Q11.1
np.random.randint(1, 1001, 6)

array([596, 107, 124, 570, 215, 738])

In [184]:
# Q11.2
np.random.rand(6)

array([0.68482974, 0.4809319 , 0.39211752, 0.34317802, 0.72904971,
       0.43857224])

In [185]:
# Q11.3
np.random.normal(700, 100, 6)

array([685.66275259, 638.08090993, 623.05665285, 757.67460214,
       712.65259202, 569.85110255])

In [186]:
# Q11.4
np.random.shuffle(banking_data)

In [187]:
# Q11.5
np.random.seed(123)
np.random.rand(4)

array([0.69646919, 0.28613933, 0.22685145, 0.55131477])

In [188]:
#Question 12: Linear Algebra Operations

In [189]:
# Q12.1
np.dot(banking_data[:,1], banking_data[:,2])

np.int64(738700000)

In [190]:
np.cross(banking_data[0, :3], banking_data[1, :3])

array([-27500000,    -12140,   5110000])

In [191]:
# Q12.3
np.linalg.norm(banking_data[:,1])

np.float64(387330.60813728627)

In [192]:
# Q12.4
A = np.array([[2, 3, 1],
              [4, 5, 6],
              [7, 8, 9]])
np.linalg.det(A)

np.float64(9.000000000000005)

In [193]:
# Q12.5
np.linalg.inv(A)

array([[-0.33333333, -2.11111111,  1.44444444],
       [ 0.66666667,  1.22222222, -0.88888889],
       [-0.33333333,  0.55555556, -0.22222222]])

In [194]:
#Question 13: String Operations

In [195]:
# Q13.1
cust_ids_str = banking_data[:, 0].astype(str)

In [196]:
# Q13.2
contains_100 = np.char.find(cust_ids_str, '100') >= 0

In [197]:
# Q13.3
cust_ids_upper = np.char.upper(cust_ids_str)

# Q13.4
cust_ids_length = np.char.str_len(cust_ids_str)

# Q13.5
cust_ids_replaced = np.char.replace(cust_ids_str, '100', 'CUST')

In [198]:
#Question 14: Date and Time Operations
# Q14.1
years_active = banking_data[:, 3]
months_active = years_active * 12

# Q14.2
avg_years_active = np.mean(years_active)

# Q14.3
active_gt5 = banking_data[years_active > 5]

# Q14.4
total_years_active = np.sum(years_active)

# Q14.5
shortest_active_customer = banking_data[np.argmin(years_active)]

In [199]:
#Question 15: Advanced Array Operations

In [200]:
# Q15.1
balances = banking_data[:, 1]
interest_balances = balances * 1.05

In [201]:
# Q15.2
balance_categories = np.where(balances < 50000, "Low",
                     np.where(balances <= 100000, "Medium", "High"))

In [202]:
# Q15.3
credit_scores = banking_data[:, 2]
conditions = [
    (credit_scores < 600),
    (credit_scores >= 600) & (credit_scores < 700),
    (credit_scores >= 700) & (credit_scores < 800),
    (credit_scores >= 800)
]
choices = ["Poor", "Fair", "Good", "Excellent"]
credit_categories = np.select(conditions, choices, default="Unknown")

In [203]:
# Q15.4
interest_rates = np.piecewise(
    balances,
    [balances < 50000, (balances >= 50000) & (balances <= 100000), balances > 100000],
    [lambda x: x * 1.02, lambda x: x * 1.03, lambda x: x * 1.05]
)

In [204]:
# Q15.5
row_sums = np.apply_along_axis(np.sum, axis=1, arr=banking_data)

In [205]:
#Question 16: Array Concatenation and Stacking

In [206]:
#Q16.1
array1=np.array([[1,2,3],[4,5,6]])
array2=np.array([[7,8,9],[10,11,12]])
hstack_result=np.hstack((array1,array2))

In [207]:
#16.2
array1=np.array([[1,2,3],[4,5,6]])
array2=np.array([[7,8,9],[10,11,12]])
vstack_result=np.vstack((array1,array2))

In [208]:
#16.3
concat_result=np.concatenate((array1,array2),axis=0)
concat_result2=np.concatenate((array1,array2),axis=1)

In [209]:
#16.4
dstack_result=np.dstack((array1,array2))

In [210]:
#Q16.5
column_stack_result=np.column_stack((array1,array2))

In [211]:
#Question 17: Array Splitting Operations

In [220]:
arr=np.arange(12)
arr2d=np.arange(16).reshape(4,4)

In [232]:
#17.1
split_result=np.split(arr,3)

In [233]:
#17.2
split_result=np.split(arr,[3,7])

In [234]:
#17.3
hsplit_result=np.hsplit(arr2d,2)

In [235]:
#17.4
vsplit_result=np.vsplit(arr2d,2)

In [236]:
#17.5
array_split_result=np.array_split(arr,5)

In [243]:
#Question 18: Array Repetition and Tiling

In [239]:
# Q18.1
repeat_elements = np.repeat(arr, 3)

In [240]:
# Q18.2
repeat_array = np.tile(arr, 2)

In [241]:
# Q18.3
repeat_2d = np.tile(arr2d, (2, 2))

In [242]:
# Q18.4
pattern = np.tile([1, 0], 5)

In [255]:
# Q18.5
arr = np.array([1, 2, 3])
repeat_diff = np.repeat(arr, [1, 2, 3])

In [ ]:
#Question 19: Array Comparison and Logical Operations

In [259]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([1, 2, 3, 4, 5])
arr3 = np.array([1, 2, 3, 4, 6])

In [260]:
# Q19.1: Compare two arrays for equality using np.array_equal()
np.array_equal(arr1, arr2)

True

In [262]:
# Q19.2: Check if arrays are close using np.allclose()
np.allclose(arr1, arr3)

False

In [263]:
# Q19.3: Apply logical AND operation between arrays
np.logical_and(arr1 > 2, arr2 > 2)

array([False, False,  True,  True,  True])

In [264]:
# Q19.4: Apply logical OR operation between arrays
np.logical_or(arr1 > 4, arr3 > 4)

array([False, False, False, False,  True])

In [265]:
# Q19.5: Apply logical NOT operation to an array
np.logical_not(arr1 > 3)

array([ True,  True,  True, False, False])

In [267]:
#Question 20: Array Set Operations

In [266]:
arr1 = np.array([1, 2, 3, 4, 5, 5, 6, 2])
arr2 = np.array([4, 5, 6, 7, 8])

In [268]:
# Q20.1: Find unique elements in an array using np.unique()
q20_1 = np.unique(arr1)

In [269]:
# Q20.2: Find the intersection of two arrays using np.intersect1d()
np.intersect1d(arr1, arr2)

array([4, 5, 6])

In [270]:
# Q20.3: Find the union of two arrays using np.union1d()
q20_3 = np.union1d(arr1, arr2)

In [271]:
# Q20.4: Find elements in first array but not in second using np.setdiff1d()
q20_4 = np.setdiff1d(arr1, arr2)

In [272]:
# Q20.5: Find the symmetric difference between two arrays using np.setxor1d()
q20_5 = np.setxor1d(arr1, arr2)
print("Q20.5:", q20_5)

Q20.5: [1 2 3 7 8]
